name: vscode-market-publisher

on:
  release:
    types:
    - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Run npm Install 
      run: npm install
    - name: Publish
      if: success()
      run: vsce publish ${{ github.event.release.tag_name }}
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
